// <auto-generated />
namespace Nanny.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_profiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_profiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201609011733464_new_profiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
